## Q. 프론트엔드에서 비동기를 왜 처리해야 할까?

### A. 무언가를 기다려야 하는 건 유저가 아닌 브라우저의 역할이기 때문

```jsx
function asyncRequest(callBackFn) {
	// ajax: 비동기 요청을 수행하는 가상의 라이브러리
	ajax('url', function (data) {
		callBackFn(data):
	});
}
```

꽤 오랜 시간 동안 비동기 처리를 위해 콜백 함수를 사용해왔지만 요새는 단순히 이 방법만으로 비동기를 처리하는 코드는 거의 보지 못하고 있다. 콜백 기반의 비동기 처리 방식이 가지고 있었던 한계와 그 대안점으로 출현한 Promise, Async Function이 해결하고자 한 것은 무엇일까?

![스크린샷 2022-09-27 오전 11.46.36.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/381785a0-e10d-432f-b19a-32af044880ad/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2022-09-27_%E1%84%8B%E1%85%A9%E1%84%8C%E1%85%A5%E1%86%AB_11.46.36.png)

한 기업이 있다. 그리고 그 기업은 사내 프로젝트를 진행할 때 필요한 원자재가 있다면 주로 하청 업체에 수주를 맡기는 방식을 채택한다. 이렇게 되면 기업은 주요 흐름에 더 집중할 수 있게 된다. 이 때 기업이 하청 업체에 견적서를 전달하면서 그 원자재를 통해 어떤 다음 업무를 처리해야하는지 전달했다고 가정해보자. 얼핏 보면 견적서를 통해 요구 사항을 전달했기 때문에 문제가 될 것이 없어 보이는데, 사실 모든 일에는 변수가 생길 수 있는 가능성이 있다.

하청업체 내부의 변수로 인해 중간 과정에 차질이 생겼다고 해도 기업은 전체적인 처리 과정을 확실히 알 방법이 없다. 왜냐하면 이미 하청 업체에 원자재 생산 요청과 더불어 **견적서에 작성된 업무 처리의 제어권까지 위임했기 때문이다.** 따라서 기업은 원하는 결과를 얻지 못하더라도 그 과정을 중간에서 알 수 있었더라면 해결책을 강구했을 테지만 제어권이 완전히 하청 업체에 넘어가있기 때문에 불가능했고 결국 기업은 이러한 방식을 신뢰할 수 없게 된다.

방금의 예시를 브라우저의 관점으로 옮겨 코드로 작성해보자.

```jsx
function browserTasks() {
	console.log('sync task');
	asyncRequest(asyncTask);
}

function asyncRequest(callBackFn) {
	ajax('url', function (data) {
		callBackFn(data):
	});
}

function asyncTask(data) {
	console.log(data);
}
```

browserTasks가 호출 되었을 때, console.log(’sync task’)는 제어의 대상이 된다. 그에 반해 비동기 요청과 함께 전달된 콜백은 외부 라이브러리에 대한 의존성을 가지게 되어 제어권의 주체가 뒤바뀌게 된다. 즉 콜백 내부에서 데이터에 대한 예외처리는 가능하더라도 비동기 요청 - 콜백 호출로 이어지는 흐름은 외부에서 관찰하거나 제어할 수가 없다. 이렇게 제어권이 바뀌는 상황을 제어의 역전(Inversion Of Control)이라고 한다.

만약 유저가 어떤 상품의 구매 버튼을 눌렀을 때, 서버에 요청을 보내는 콜백이 이와 같은 예시 중 하나라도 해당된다면 어떻게 될까?

1. 필요한 데이터를 콜백에 전달 했는지에 대한 여부
2. 호출 시점 (빠르거나, 느리거나)
3. 호출 횟수 (호출을 아예 안하거나, 많이 호출하거나)

이러한 버그는 곧 매출에 직결된다.

처음에 들었던 기업의 예시로 돌아가보자. 기업이 원자재에 대한 요청만 견적서로 전달 후, 그에 대한 수행 결과를 가져와서 후순위 업무를 직접 처리하는 방법으로 해결할 수 있지 않을까? 이것이 바로 Promise다.

### Promise

- ES6
- 미래에 값을 반환할 수도 있는 함수를 캡슐화한 객체
- **제어의 재역전**
- **비동기 요청 수행에 대한 세 가지(성공, 실패, 대기)의 상태를 가지고 있다.**
- **내부에서 비동기 요청이 끝나고 나면 결과값을 연결된 콜백으로 보내준다.**

```jsx
function request() {
	// executor 함수
	// 콜백 함수는 Promise를 생성하면 내부 로직은 바로 실행된다
	return new Promise(function (resolve, reject) {
		ajax('url', function (data) {
			if (data) {
				resolve(data);
			} else {
				reject('Error!');
			}
		});
	});
}

function asyncTask() {
	const promise = request();
	
	promise
		.then(function (data) {
			// 받아온 data를 이용한 일련의 작업 수행
		})
		.catch(function (error) {
			// 받아온 error를 이용한 예외 처리
		})
}
			
```

이제는 더 이상 외부 라이브러리에 콜백 함수를 넘겨주지 않고, 비동기 요청에 대한 결과를 받아와서 직접 처리할 수 있게 되었다.

하지만 단점도 존재한다. Promise 객체 외부에서 Promise 내의 연쇄적인 흐름에 대한 예외처리가 어렵다. 또한 단일 값밖에 전달하지 못하기 때문에 여러 개의 값의 연관성이 부족하더라도 넘겨주려면 객체, 배열로 감싸야 한다. 마지막으로 단순 콜백 처리와 비교했을 때 성능 저하가 생긴다.

## Q. Promise와 Async Function은 왜 사용할까?

### A. 기존 콜백 방식의 신뢰성, 비동기 코드 자체의 가독성을 해결

```jsx
function A(callback) {
	console.log('A');
	setTimeout(() => callback(), 0);
}

function B() {
	console.log('B');
}

function C() {
	console.log('C');
}

A(B);

C();
```

위 코드의 실행 결과가 A → C → B임을 알기 위해서는 머리 속에 최소 두 개의 맥락을 고려해야 한다. 즉 비동기 코드의 양이 많아질수록 추론의 순서가 복잡해져 개발자들의 디버깅 작업을 어렵게 한다.

동기 코드처럼 보이게 하는 방법은 무엇이 있을까?

### Generator

- ES6
- * : generator 함수를 작성하기 위한 규칙. function 키워드 뒤나 식별자 앞에 선언한다.
- Iterator: generator 호출로 반환된 객체. next()를 가지고 있다.
- next(): generator 함수 안의 yield 문으로 넘어가기 위한 메서드
- yield: next()가 호출 되었을 때, 1) 중간에 멈추고 2) 데이터를 받는 지점

```jsx
function *asyncTask() {
	const data = yield request();

	// 받아온 data를 이용한 일련의 작업 수행
}

function request() {
	ajax('url', function (data) {
		it.next(data);
	});
}

const it = asyncTask();

it.next();
```

asyncTask라는 제너레이터 함수를 호출해 iterator 객체를 반환한 뒤 이 객체의 next() 메서드를 호출하면 연결된 함수를 수행하다가 첫 번째 yield문 뒤에 있는 request()를 호출하고 함수를 중단한다.

그리고 비동기 요청을 마치고 값을 받아오면, 받아온 값을 중단된 지점으로 보내어 함수를 재개한다.

정리해보면 제너레이터를 이용한 방식은 ‘함수를 도중에 중단할 수 있다’ 라는 특징과 ‘함수의 중간 지점에 값을 보낼 수 있다’라는 특징을 조합하여 외부의 값을 기다렸다가 받은 시점에서 함수를 실행한다.

### Async Function

- ES2017
- Syntatic Sugar
- 함수 내에서 await 문을 만나면 함수의 실행을 일시 중지
- await 뒤에 있는 프로미스의 수행 결과 값을 받아 함수 재진행

Async Function은 ES2017에 출현한 문법이며 Promise에 Generator를 더한 일종의 Syntatic sugar로 소개되었다.

```jsx
async function asyncTask() {
	const data = await request();

	// 받아온 data를 이용한 일련의 작업 수행
}

function request() {
	return new Promise(resolve => {
		ajax('url', function (data) {
			resolve(data);
		});
	});
}
```

한 눈에 봐도 가독성이 개선되었다. 이 함수 안에 선언된 await문은 뒤에 있는 주체가 Promise일 때만 그 간극을 기다린다. 그리고 만약 Promise 내부 수행 과정에서 에러가 발생한다면 해당 에러를 throw한 것과 동일한 동작을 수행하고 에러가 발생하지 않으면 Promise의 결과 값을 반환하게 된다. async function 사용을 통하여 가독성 향상은 물론 폭넓은 예외 처리까지 가능하게 됐다.

하지만 여전히 하나의 함수 안에서 다수의 Promise를 병렬적으로 처리할 수 없다. 경우에 따라 asnyc 키워드를 관련 함수마다 일일이 선언해야 할 수도 있다.

## 다수의 Promise를 처리하는 방법

### Promise.all()

```jsx
onClick = async () => {
  console.time("ABC");
  try {
    const data001 = new Promise((resolve) =>
      setTimeout(resolve, 3000, "promise001")
    );

    const data002 = Promise.reject("promise002 reject");

    const data003 = await Promise.all([data001, data002]);
    console.log(data003);
  } catch (error) {
    console.error(error);
  } finally {
    console.timeEnd("ABC");
  }
```

Promise.all() 함수는 전달된 Promise에서 하나라도 실패하면, 즉시 reject한다.

### Promise.allSettled()

```jsx
onClick = async () => {
  console.time("ABC");
  try {
    const data001 = new Promise((resolve) =>
      setTimeout(resolve, 3000, "promise001")
    );

    const data002 = Promise.reject("promise002 reject");

    const data003 = await Promise.allSettled([data001, data002]);
    console.log(data003);
  } catch (error) {
    console.error(error);
  } finally {
    console.timeEnd("ABC");
  }
};
```

Promise에서 reject되었는지 여부에 관계없이 해결된 Promise를 반환한다.

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/bf37fecf-9f24-4a53-8dd0-390027ff079c/Untitled.png)

### Promise.race()

```jsx
const promise1 = new Promise((resolve, reject) => {
  setTimeout(resolve, 500, 'one');
});

const promise2 = new Promise((resolve, reject) => {
  setTimeout(resolve, 100, 'two');
});

Promise.race([promise1, promise2]).then((value) => {
  console.log(value);
  // Both resolve, but promise2 is faster
});
// expected output: "two"
```

가장 먼저 완료된 것의 결과값으로 그대로 이행하거나 reject한다.

### Promise.any()

```jsx
const promise1 = Promise.reject(0);
const promise2 = new Promise((resolve) => setTimeout(resolve, 100, 'quick'));
const promise3 = new Promise((resolve) => setTimeout(resolve, 500, 'slow'));

const promises = [promise1, promise2, promise3];

Promise.any(promises).then((value) => console.log(value));

// expected output: "quick"
```

가장 빨리 fulfilled 처리된 Promise의 결과값을 반환한다. 어떤 Promise도 fulfilled되지 않았다면 AggregateError와 함께 reject한다.

[[10분 테코톡] 📖 카일의 프론트엔드의 비동기](https://www.youtube.com/watch?v=fsmekO1fQcw&t=382)

[function* - JavaScript | MDN](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/function*)

[[JavaScript]Promise 병렬 처리](https://developer-talk.tistory.com/464)

[Promise.race() - JavaScript | MDN](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/race)

[Promise.any() - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any)
